const USERNAME_MIN_LENGTH = 3;
const USERNAME_MAX_LENGTH = 30;
const USERNAME_REGEX = /^[\p{L}\p{N}_]+$/u;

const DISPLAY_NAME_MAX_LENGTH = 50;

const PASSWORD_MIN_LENGTH = 8;
const PASSWORD_MAX_LENGTH = 128;

export const constants = {
	USERNAME_MIN_LENGTH,
	USERNAME_MAX_LENGTH,
	USERNAME_REGEX,
	DISPLAY_NAME_MAX_LENGTH,
	PASSWORD_MIN_LENGTH,
	PASSWORD_MAX_LENGTH,
} as const;
